import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        canvas: {
          DEFAULT: "hsl(var(--canvas))",
          soft: "hsl(var(--canvas-soft))",
          dark: "hsl(var(--canvas-dark))",
          deeper: "hsl(var(--canvas-deeper))",
        },
        ink: {
          DEFAULT: "hsl(var(--ink))",
          charcoal: "hsl(var(--ink-charcoal))",
          muted: "hsl(var(--ink-muted))",
          stone: "hsl(var(--ink-stone))",
        },
        hairline: {
          DEFAULT: "hsl(var(--hairline))",
          soft: "hsl(var(--hairline-soft))",
        },
        "on-dark": {
          DEFAULT: "hsl(var(--on-dark))",
          muted: "hsl(var(--on-dark-muted))",
        },
        combat: "hsl(var(--combat-red))",
        amber: "hsl(var(--amber-signal))",
        steel: "hsl(var(--slate-steel))",
        orb: {
          peach: "hsl(var(--orb-peach))",
          sky: "hsl(var(--orb-sky))",
          lavender: "hsl(var(--orb-lavender))",
        },
        ai: {
          gpt: "#FEF9EE",
          claude: "#E8F4EE",
          gemini: "#E8F0FE",
          grok: "#FDE8E8",
          deepseek: "#E8ECF4",
          perplexity: "#F0EDF8",
          llama: "#F0EEE8",
          qwen: "#E8F4F2",
          kimi: "#FEF4E8",
        },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
      },
      fontFamily: {
        display: ['"Playfair Display"', "serif"],
        mono: ['"DM Mono"', "ui-monospace", "monospace"],
        sans: ['"DM Sans"', "system-ui", "sans-serif"],
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "pulse-dot": { "0%,100%": { opacity: "1" }, "50%": { opacity: ".3" } },
        "slide-up-fade": { "0%": { opacity: "0", transform: "translateY(20px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-dot": "pulse-dot 2s ease-in-out infinite",
        "slide-up-fade": "slide-up-fade 0.3s cubic-bezier(0.22,1,0.36,1) both",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
